apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{value.app_name}}
  description: Python Application for demonstration purposes
  annotations:
    github.com/project-slug: rakshay07-org/${{value.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental